#!/usr/bin/env python3
"""Emit textures/icons.h from icons.png (Minecraft textures/gui/icons.png).

Vanilla atlas is 256×256; if the source is larger (e.g. 768×768 HD), it is resized to 256
so UVs match Java Edition / MCP GuiIngame (1.4.x–1.12 use the same sheet layout).

Regenerate: python3 textures/gen_icons_h.py
"""
from __future__ import annotations

import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.stderr.write("Install Pillow: pip install pillow\n")
    sys.exit(1)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PNG_PATH = os.path.join(SCRIPT_DIR, "icons.png")
OUT_PATH = os.path.join(SCRIPT_DIR, "icons.h")
TARGET = (256, 256)


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> None:
    if not os.path.isfile(PNG_PATH):
        sys.stderr.write(f"Missing {PNG_PATH}\n")
        sys.exit(1)

    im = Image.open(PNG_PATH).convert("RGBA")
    if im.size != TARGET:
        im = im.resize(TARGET, Image.LANCZOS)

    w, h = im.size
    pixels: list[int] = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = im.getpixel((x, y))
            if a < 128:
                pixels.append(0x0000)
            elif r <= 1 and g <= 1 and b <= 1:
                pixels.append(0x0841)
            else:
                pixels.append(rgb888_to_rgb565(r, g, b))

    lines = [
        "// Generated by textures/gen_icons_h.py from textures/icons.png (256×256, MCP / 1.4.7+ HUD UVs).",
        "static uint16_t icons_data[] = {",
    ]
    per_line = 12
    for i in range(0, len(pixels), per_line):
        chunk = pixels[i : i + per_line]
        sep = "," if i + per_line < len(pixels) else ""
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + sep)
    lines.append("};")
    lines.append("")
    lines.append("static TEXTURE icons{")
    lines.append(f"    {w}, {h},")
    lines.append("    true, 0,")
    lines.append("    icons_data")
    lines.append("};")
    lines.append("")

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {OUT_PATH} ({w}×{h})", file=sys.stderr)


if __name__ == "__main__":
    main()
